---
title: ""
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(lubridate)
library(plm)
library(lmtest)
library(clubSandwich)
library(modelsummary)

options(scipen = 999)

data <- read_csv(here::here("data",
                            "monthly-county-combined-dataset.csv"))



data <- data %>% 
  filter(month >= "2020-01-01",
         month < "2021-03-01") %>% 
  mutate(across(c(cases, deaths),
                ~ ifelse(is.na(.),
                         0,
                         .))) %>% 
  mutate(cases_per_capita = cases / population,
         deaths_per_capita = deaths / population) %>% 
  filter(!is.na(fips))


```

## Robustness check: Rolling Panel

```{r}

panel_model_6mo <- function(dataframe,
                            start_date,
                            n_months) {
  
  
  mdata <- dataframe %>% 
    filter(month >= start_date,
           month < ymd(start_date) + days(30 * n_months))
  
  
  mod_it_rent <- plm(rent_index ~ cases_per_capita + deaths_per_capita 
                     + avg_temp + unemployment_rate,
                     data = mdata,
                     index = c("fips", "month"),
                     model = "within",
                     effect = "twoways") %>% 
    broom::tidy() %>% 
    mutate(model_type = "Rent index",
           start_date = start_date,
           months = paste0(n_months, " month rolling window"))
  
  mod_it_own <- plm(zhvi_index ~ cases_per_capita + deaths_per_capita 
                    + avg_temp + unemployment_rate,
                    data = mdata,
                    index = c("fips", "month"),
                    model = "within",
                    effect = "twoways") %>% 
    broom::tidy() %>% 
    mutate(model_type = "Home price index",
           start_date = start_date,
           months = paste0(n_months, " month rolling window"))
  
  bind_rows(mod_it_rent,
            mod_it_own)
}


results <- map_df(.x = ymd("2020-01-01") + months(0:8),
                  ~ panel_model_6mo(dataframe = data,
                                    start_date = .x,
                                    n_months = 6))

results4 <- map_df(.x = ymd("2020-01-01") + months(0:10),
                  ~ panel_model_6mo(dataframe = data,
                                    start_date = .x,
                                    n_months = 4))

results8 <- map_df(.x = ymd("2020-01-01") + months(0:6),
                  ~ panel_model_6mo(dataframe = data,
                                    start_date = .x,
                                    n_months = 8))

rolling_coef_plot <- function(results_df,
                              variable,
                              n_months = 6) {
  
  
  results_df %>% 
    filter(term == variable) %>% 
    ggplot(aes(x = start_date, y = estimate, color = model_type)) +
    geom_hline(yintercept = 0) +
    geom_point(position = position_dodge(width = 5)) +
    geom_errorbar(aes(ymin = estimate - 1.96*std.error,
                      ymax = estimate + 1.96*std.error),
                  position = position_dodge(width= 5)) +
    theme_minimal() +
    scale_x_date(date_breaks = "1 month",
                 date_labels = "%b-%y") +
    labs(x = str_glue("Start date of {n_months}-month period"),
         y = NULL,
         color = NULL) +
    theme(legend.position = "top") +
    scale_color_manual(values = c("#00799e", "#ffa604"))
  
}

```


### Cases per capita {.tabset .tabset-fade}

#### 4-month

```{r}
rolling_coef_plot(results_df = results4,
                  variable = "cases_per_capita",
                  n_months = 4)
```

#### 6-month

```{r}
rolling_coef_plot(results_df = results,
                  variable = "cases_per_capita",
                  n_months = 6)
```

#### 8-month

```{r}
rolling_coef_plot(results_df = results8,
                  variable = "cases_per_capita",
                  n_months = 8)
```

### Average monthly temperature {.tabset .tabset-fade}

#### 4-month

```{r}
rolling_coef_plot(results_df = results4,
                  variable = "avg_temp",
                  n_months = 4)
```


#### 6-month

```{r}
rolling_coef_plot(results_df = results,
                  variable = "avg_temp",
                  n_months = 6)
```

#### 8-month

```{r}
rolling_coef_plot(results_df = results8,
                  variable = "avg_temp",
                  n_months = 8)
```

### Unemployment rate {.tabset .tabset.fade}

#### 4-month

```{r}
rolling_coef_plot(results_df = results4,
                  variable = "unemployment_rate",
                  n_months = 4)

```

#### 6-month

```{r}
rolling_coef_plot(results_df = results,
                  variable = "unemployment_rate",
                  n_months = 6)

```


#### 8-month

```{r}
rolling_coef_plot(results_df = results8,
                  variable = "unemployment_rate",
                  n_months = 8)

```


## Faceted charts for report

```{r}
rolling_coef_plot_facet <- function(results_df,
                              variable) {
  
  
  results_df %>% 
    filter(term == variable) %>% 
    ggplot(aes(x = start_date, y = estimate, color = model_type)) +
    geom_hline(yintercept = 0) +
    geom_point(position = position_dodge(width = 5)) +
    geom_errorbar(aes(ymin = estimate - 1.96*std.error,
                      ymax = estimate + 1.96*std.error),
                  position = position_dodge(width= 5)) +
    theme_minimal() +
    scale_x_date(date_breaks = "2 months",
                 date_labels = "%b-%y") +
    labs(x = str_glue("Start date of period"),
         y = NULL,
         color = NULL) +
    theme(legend.position = "top") +
    scale_color_manual(values = c("#00799e", "#ffa604")) +
    facet_wrap(~months)
  
}


r <- bind_rows(results, results4, results8)

rolling_coef_plot_facet(results_df = r,
                  variable = "cases_per_capita") 
ggsave(here::here("figures",
                  "cases-window-comp.png"),
                  width = 7.5, height = 5)

rolling_coef_plot_facet(results_df = r,
                  variable = "avg_temp") 
ggsave(here::here("figures",
                  "temp-window-comp.png"),
                  width = 7.5, height = 5)

rolling_coef_plot_facet(results_df = r,
                  variable = "unemployment_rate") 
ggsave(here::here("figures",
                  "unemployment-window-comp.png"),
                  width = 7.5, height = 5)

```