---
title: "Time invariant model"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(plm)
library(lmtest)
library(clubSandwich)
library(modelsummary)

options(scipen = 999)

data <- read_csv(here::here("data",
                            "monthly-county-combined-dataset.csv"))



pit <- data %>% 
  group_by(fips, county_name) %>% 
  summarize(population = mean(population),
            population_per_sqmile = mean(population_per_sqmile),
            rural_classifiction = mean(rural_classification, na.rm = TRUE),
            total_covid_cases = sum(cases, na.rm = TRUE),
            cases_per_capita = total_covid_cases / population,
            total_covid_deaths = sum(deaths, na.rm = TRUE),
            deaths_per_capita = total_covid_deaths / population,
            total_executive_orders = mean(total_executive_orders),
            governor_party = governor_party[1],
            jan_temp = avg_temp[month == "2021-01-01"],
            july_temp = avg_temp[month == "2020-07-01"],
            rent_now = rent[month == "2021-02-01"],
            rent_then = rent[month == "2020-02-01"],
            homeprice_now = zhvi[month == "2021-02-01"],
            homeprice_then = zhvi[month == "2020-02-01"],
            pmms_change = pmms[month == "2020-03-01"] - pmms[month == "2020-02-01"],
            rent_change = (rent_now - rent_then) / rent_then * 100,
            homeprice_change = (homeprice_now - homeprice_then) / homeprice_then * 100,
            unemployment_rate_change = unemployment_rate[month == "2020-02-01"] -
              unemployment_rate[month == "2021-02-01"],
            rent_change_dollar = rent_now - rent_then,
            homeprice_change_dollar = homeprice_now - homeprice_then) %>% 
  ungroup() %>% 
  mutate(republican_governor = ifelse(governor_party == "Republican",
                                      1,
                                      0))

```

```{r}

pit <- pit %>% 
  mutate(rent_change_abs = abs(rent_change_dollar),
         rent_decrease = ifelse(rent_change_dollar < 0,
                                1,
                                0),
         homeprice_change_abs = abs(homeprice_change_dollar),
         homeprice_decrease = ifelse(homeprice_change_dollar < 0,
                                     1,
                                     0))

# summarize(pit,
#           rent_decrease = sum(rent_decrease, na.rm = TRUE),
#           homeprice_decrease = sum(homeprice_decrease, na.rm = TRUE))
# 
# pit %>% 
#   filter(rent_decrease == 1) %>% 
#   summarize(mean(rent_change))
# 
# pit %>% 
#   summarize(mean(homeprice_change,
#                  na.rm = TRUE))

```

```{r, message=FALSE}


pit <- pit %>% 
  mutate(rent_change_abs = abs(rent_change_dollar),
         rent_increase = ifelse(rent_change_dollar < 0,
                                0,
                                1),
         homeprice_change_abs = abs(homeprice_change_dollar),
         homeprice_increase = ifelse(homeprice_change_dollar < 0,
                                     0,
                                     1))

m1 <- lm(rent_change ~ cases_per_capita +
           rent_then +
           #rent_decrease +
           jan_temp +
           population_per_sqmile + 
           unemployment_rate_change +
           republican_governor +
           total_executive_orders,
         data = pit)

m2 <- lm(homeprice_change ~ cases_per_capita +
           homeprice_then +
           #homeprice_decrease +
           jan_temp +
           population_per_sqmile + 
           unemployment_rate_change +
           republican_governor +
           total_executive_orders,
         data = pit)

modelsummary(list("Rent change" = m1,
                  "Home price change" = m2),
             stars = TRUE,
             vcov = "HC1",
             gof_omit = "AIC|BIC|Log.Lik")


modelplot(list("Rent change" = m1,
               "Home price change" = m2),
          vcov = "HC1",
          coef_omit = "(Intercept)|republican_governor",
          coef_rename = c("cases_per_capita" ="Cases per capita",
                          "rent_then" = "Rent, pre-pandemic",
                          "jan_temp" ="January average temperature",
                          "population_per_sqmile" ="Population per square mile",
                          "unemployment_rate_change" = "Unemployment rate change",
                          "total_executive_orders" = "Total executive orders",
                          "homeprice_then" = "Home prices, pre-pandemic")) +
  scale_color_manual(values = c("#00799e", "#ffa604"))

ggsave(here::here("figures",
                  "time-invariant-model-plot.png"))

modelplot(m1,
          vcov = "HC1",
          coef_omit = "(Intercept)|republican_governor",
          coef_rename = c("cases_per_capita" ="Cases per capita",
                          "rent_then" = "Rent, pre-pandemic",
                          "jan_temp" ="January average temperature",
                          "population_per_sqmile" ="Population per square mile",
                          "unemployment_rate_change" = "Unemployment rate change",
                          "total_executive_orders" = "Total executive orders",
                          "homeprice_then" = "Home prices, pre-pandemic"))

ggsave(here::here("figures",
                  "time-invariant-model-plot.png"),
       width = 6, height = 6)

```